### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by donlelef** [WhiskeyInc/XP-team-tools#1]
I played a bit with the tests and I saw there are a lot of unhandled 'nullPointerException'. For example, an exception is lauched when a task is added to an unexisting 'UserStory'.  
The question is: shall we try to handle them all in the UI, or it is better to create a specific exception for every issue?
I think the second possibility is better. @simone3991 @AlessandroIncremona ?

**Comment by simone3991** [comment]
If i'm searching for an item (no matter what) that does not exist, i do expect some kind of exception. Therefore, i think it would be better to throw necessary exceptions in the app's logic rather than avoiding those kind of situations in the GUI. It makes our system stronger and more solid!

**Comment by donlelef** [comment]
I agree! Moreover, some exceptions have been created but are still unused. For example, NoSuchUserStoryException.

**Comment by AlessandroIncremona** [comment]
I agree too!

**Comment by donlelef** [comment]
One exception for every fault. Issue closed.
